language: cpp

addons:
  apt:
    packages:
    - libtool
    - libxml2-dev
    - libgeos-dev
    - libgeos++-dev
    - libpq-dev
    - libbz2-dev
    - libproj-dev
    - protobuf-c-compiler
    - libprotobuf-c0-dev

matrix:
  include:
    #basic tests of with/without lua and old boost versions, with both clang and gc
    - os: linux
      compiler: clang
      env: USE_LUA=true
    - os: linux
      compiler: clang
      env: USE_LUA=true BOOST_PPA=1.55
    - os: linux
      compiler: clang
      env: USE_LUA=false BOOST_PPA=1.55
    - os: linux
      compiler: gcc
      env: USE_LUA=true
    - os: linux
      compiler: gcc
      env: USE_LUA=true BOOST_PPA=1.55
    - os: linux
      compiler: gcc
      env: USE_LUA=false BOOST_PPA=1.55
    # additional tests
    - os: linux
      compiler: clang
      env: USE_LUA=true BOOST_PPA=1.54
    # OS X tests
    - os: osx
      compiler: clang
      env: USA_LUA=true
before_install:
  # BOOST_PPA is only set on linux
  - if [ -z ${BOOST_PPA+x} ]; then
      echo "Using system Boost";
    else
      echo "Using Boost PPA";
      sudo add-apt-repository -y ppa:boost-latest/ppa;
    fi
  - if [[ $(uname -s) == 'Linux' ]]; then
      sudo apt-get update -qq;
    else
      brew update;
    fi
install:
  - if [[ $(uname -s) == 'Linux' ]]; then
      if [ -z ${BOOST_PPA+x} ]; then
        sudo apt-get install -y -qq libboost1.48-all-dev;
      else
        sudo apt-get install -y -qq "boost${BOOST_PPA}";
      fi;
      if [[ "${USE_LUA}" = "true" ]]; then
        sudo apt-get install -y -qq lua5.2 liblua5.2-dev;
      fi;
    else
      brew install protobuf protobuf-c postgresql lua libxml2 libtool geos boost;
    fi
before_script:
  - xml2-config --version
  - geos-config --version
  - proj | head -n1
  - if [ "${USE_LUA}" = "true" ]; then
      lua -v;
    fi;
script:
  ./autogen.sh && ./configure && make -j2
after_failure:
  - cat config.log
