environment:
  global:
    BZIP2_VER: 1.0.8.0
    EXPAT_VER: 2.2.5
    PROJ4_VER: 4.9.3
    ZLIB_VER: 1.2.11
    LUA_VER: 5.3.4
    LUA_INCLUDE_DIR: C:\lua\include
    LUA_LIBRARIES: C:\lua\lua53.lib
    LUA_DLL: C:\lua\lua53.dll
    WINGETOPT_VER: v0.95
    GETOPT_INCLUDE_DIR: C:\wingetopt\src
    GETOPT_LIBRARY: C:\wingetopt\build\wingetopt.lib
    BZIP2_INCLUDE_DIR: C:\bzip2\dev
    BZIP2_LIBRARY: C:\bzip2\dll
    PGUSER: postgres
    PGPASSWORD: Password12!

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      MSVC_SETUP_PATH: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      MSVC_SETUP_ARG: amd64
      BOOST_PATH: C:\Libraries\boost_1_63_0
      POSTGRESQL_VER: 11.2
      POSTGIS_URL: https://osm2pgsql.org/ci/winbuild/postgis-bundle-pg96-2.5.3x64.zip
      POSTGIS_DIR: postgis-bundle-pg96-2.5.3x64
      POSTGRES_DIR: C:\Progra~1\PostgreSQL\9.6
      POSTGRES_SERVICE: postgresql-x64-9.6

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      MSVC_SETUP_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat
      MSVC_SETUP_ARG:
      BOOST_PATH: C:\Libraries\boost_1_71_0
      POSTGRESQL_VER: 11.2
      POSTGIS_URL: http://osm2pgsql.org/ci/winbuild/postgis-bundle-pg12-3.0.3x64.zip
      POSTGIS_DIR: postgis-bundle-pg12-3.0.3x64
      POSTGRES_DIR: C:\Progra~1\PostgreSQL\12
      POSTGRES_SERVICE: postgresql-x64-12
# Workaround pg bug
      PGGSSENCMODE: disable

# Original locations for PostGIS:
# https://download.osgeo.org/postgis/windows/pg96/archive/postgis-bundle-pg96-2.5.3x64.zip
# https://download.osgeo.org/postgis/windows/pg12/archive/postgis-bundle-pg12-3.0.3x64.zip


clone_folder: c:\osm2pgsql

clone_depth: 1

init:
  - git config --global core.autocrlf input
  - set bz2_dll_url=https://github.com/philr/bzip2-windows/releases/download/v%BZIP2_VER%/bzip2-dll-%BZIP2_VER%-win-x64.zip
  - set bz2_dev_url=https://github.com/philr/bzip2-windows/releases/download/v%BZIP2_VER%/bzip2-dev-%BZIP2_VER%-win-x64.zip
  - set conda_path=C:\Miniconda36-x64\Scripts
  - set python_path=C:\Python38-x64
  - set conda_library_path=C:\Miniconda36-x64\envs\osm2pgsql\Library
  - set lua_url=https://osm2pgsql.org/ci/winbuild/lua_x64.zip
  - set build_type=Release
  - call "%MSVC_SETUP_PATH%" %MSVC_SETUP_ARG%

install:
  - set PATH=%TESTS_POSTGRESQL_ROOT%\bin;%python_path%;%PATH%;%conda_path%
  - cd c:\
  - conda config --set always_yes yes
  - conda create --name osm2pgsql
  - activate osm2pgsql
  - conda install expat=%EXPAT_VER% proj4=%PROJ4_VER% zlib=%ZLIB_VER% postgresql=%POSTGRESQL_VER%
  - ps: if (!(Test-Path "C:\bzip2_dll_x64.zip")){(new-object net.webclient).DownloadFile($env:bz2_dll_url, "C:\bzip2_dll_x64.zip")}
  - 7z x -y C:\bzip2_dll_x64.zip -o%BZIP2_LIBRARY%
  - ps: if (!(Test-Path "C:\bzip2_dev_x64.zip")){(new-object net.webclient).DownloadFile($env:bz2_dev_url, "C:\bzip2_dev_x64.zip")}
  - 7z x -y C:\bzip2_dev_x64.zip -o%BZIP2_INCLUDE_DIR%
  - ps: if (!(Test-Path "C:\lua_x64.zip")){(new-object net.webclient).DownloadFile($env:lua_url, "C:\lua_x64.zip")}
  - 7z x -y C:\lua_x64.zip -oC:\lua
  - ps: if (!(Test-Path "C:\postgis.zip")){(new-object net.webclient).DownloadFile($env:POSTGIS_URL, "C:\postgis.zip")}
  - 7z x C:\postgis.zip -oC:\postgis
  - xcopy /e /y /q C:\postgis\%POSTGIS_DIR% %POSTGRES_DIR%
  - git clone https://github.com/alex85k/wingetopt -b %WINGETOPT_VER% C:\wingetopt
  - python -V
  - python -m pip install psycopg2

before_build:
  - cd C:\wingetopt
  - mkdir build
  - cd build
  - cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=%build_type%
  - nmake

build_script:
  - mkdir c:\osm2pgsql\build
  - cd c:\osm2pgsql\build
  - >
    cmake .. -LA -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=%build_type% -DBUILD_TESTS=ON
    -DLUA_INCLUDE_DIR=%LUA_INCLUDE_DIR% -DLUA_LIBRARIES=%LUA_LIBRARIES% 
    -DGETOPT_INCLUDE_DIR=%GETOPT_INCLUDE_DIR% -DGETOPT_LIBRARY=%GETOPT_LIBRARY%
    -DBOOST_ROOT=%BOOST_PATH% -DBoost_USE_STATIC_LIBS=ON
    -DBZIP2_INCLUDE_DIR=%BZIP2_INCLUDE_DIR%
    -DBZIP2_LIBRARIES=%BZIP2_INCLUDE_DIR%\libbz2.lib
  - nmake

after_build:
  - mkdir osm2pgsql-bin
  - copy /y *.exe osm2pgsql-bin
  - copy /y ..\*.style osm2pgsql-bin
  - copy /y ..\*.lua osm2pgsql-bin
  - copy /y %conda_library_path%\bin\libpq.dll osm2pgsql-bin
  - copy /y %conda_library_path%\bin\zlib.dll osm2pgsql-bin
  - copy /y %conda_library_path%\bin\expat.dll osm2pgsql-bin
  - copy /y %conda_library_path%\bin\gssapi64.dll osm2pgsql-bin
  - copy /y %conda_library_path%\bin\libcrypto-1_1-x64.dll osm2pgsql-bin
  - copy /y %conda_library_path%\bin\libssl-1_1-x64.dll osm2pgsql-bin
  - copy /y %conda_library_path%\bin\comerr64.dll osm2pgsql-bin
  - copy /y %conda_library_path%\bin\krb5_64.dll osm2pgsql-bin
  - copy /y %conda_library_path%\bin\k5sprt64.dll osm2pgsql-bin
  - copy /y %conda_library_path%\bin\*.dll osm2pgsql-bin
  - del /q osm2pgsql-bin\api-ms-win*.dll
  - copy /y %BZIP2_LIBRARY%\libbz2.dll osm2pgsql-bin
  - copy /y %LUA_DLL% osm2pgsql-bin
  - 7z a c:\osm2pgsql\osm2pgsql_%build_type%_x64.zip osm2pgsql-bin -tzip

before_test:
  - net start "%POSTGRES_SERVICE%"
  - cd c:\
  - mkdir temp
  - cacls temp /T /E /G Users:F
  - cacls temp /T /E /G "Network Service":F
  - |
    psql -c "CREATE TABLESPACE tablespacetest LOCATION 'c:/temp'"
  - set PATH=c:\osm2pgsql\build\osm2pgsql-bin;%PATH%
  - set PROJ_LIB=%conda_library_path%\share

test_script:
  - cd c:\osm2pgsql\build
  #- ctest -VV -L NoDB
  - ctest -VV -LE FlatNodes # enable when Postgis will be available

artifacts:
  - path: osm2pgsql_%build_type%_x64.zip

on_failure:
  - appveyor PushArtifact CMakeFiles/CMakeOutput.log
  - appveyor PushArtifact CMakeFiles/CMakeError.log
# Start up RDP server on AppVeyor for troubleshooting
#  - reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" /v UserAuthentication /t REG_DWORD /d 0 /f
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


cache:
  - C:\lua_x64.zip -> appveyor.yml
  - C:\bzip2_dev_x64.zip -> appveyor.yml
  - C:\bzip2_dll_x64.zip -> appveyor.yml
  - C:\postgis.zip -> appveyor.yml
